DiyetisyenProje/DiyetisyenProje/Areas/Admin/Controllers/AdminAboutController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;

namespace DiyetisyenProje.Areas.Admin.Controllers
{
    [Area("Admin")]  
    public class AdminAboutController : Controller
    {
        AboutManager aboutManager = new AboutManager(new EfAboutDal());
        private readonly IWebHostEnvironment _he;

        public AdminAboutController(IWebHostEnvironment he)
        {
            _he = he;
        }

        public IActionResult Index()
        {
            var values=aboutManager.GetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            var values=aboutManager.TGetById(id);
            return View(values);    
        }
        [HttpPost]
        public IActionResult Update(About about)
        {
            var files = HttpContext.Request.Form.Files;
            if (files.Count > 0)
            {
                var filename = Guid.NewGuid().ToString();
                var uploads = Path.Combine(_he.WebRootPath, @"resim");
                var ext = Path.GetExtension(files[0].FileName);
                if (about.Image != null)
                {
                    var imagePath = Path.Combine(_he.WebRootPath, about.Image.TrimStart('\\'));
                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }
                }
                using (var fileStream = new FileStream(Path.Combine(uploads, filename + ext), FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }
                about.Image = @"\resim\" + filename + ext;
            }
            aboutManager.TUpdate(about);
            return RedirectToAction("Index");   
        }
    }
}

DiyetisyenProje/DiyetisyenProje/Areas/Admin/Views/AdminAbout/Index.cshtml
@using EntityLayer.Concrete
@model List<About>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container">
    <table class="table table-bordered table-striped" id="myTable">
        <thead>
            <tr>
                <th>
                    Resim
                </th>
                <th>
                    Ad
                </th>
                <th>
                    Soyad
                </th>
                <th>
                    Hakkımda
                </th>
                <th>
                    Deneyim
                </th>
                <th>
                    Şehir
                </th>

                <th>Düzenle</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @if (item.Image != null)
                        {
                            <img src="@item.Image" width="85" height="85" />}
                        else
                        {
                            <img src="/dietician/images/resim-yok.jpg" width="85" height="85" />
                        }

                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Surname
                    </td>
                    <td>
                        @item.AboutMe
                    </td>
                    <td>
                        @item.Experience
                    </td>
                    <td>
                        @item.City
                    </td>
                    <td>
                        @item.Image
                    </td>
                    <td>
                        <a href="/Admin/AdminAbout/Update/@item.AboutId">Düzenle</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

    @section Scripts{
        <script type="text/javascript">
            $(document).ready(function () {
                $('#myTable').DataTable({
                    language: {
                        "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json",
                    },
                });
            });
        </script>
    }

DiyetisyenProje/DiyetisyenProje/Areas/Admin/Views/AdminAbout/Update.cshtml
@model EntityLayer.Concrete.About
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="AdminAbout" asp-action="Update"  method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div>
        <input type="hidden" asp-for="AboutId" />
    </div>
    <div class="form-group">
        <label class="control-label">Resim</label>
        <input asp-for="Image" type="hidden" class="form-control" />
        <input asp-for="Image" type="file" class="form-control" />
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label">İsim</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label">Soyisim</label>
        <input asp-for="Surname" class="form-control" />
        <span asp-validation-for="Surname" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label">Şehir</label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label">Deneyim</label>
        <input asp-for="Experience" class="form-control" />
        <span asp-validation-for="Experience" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label">Deneyim</label>
        <input asp-for="AboutMe" class="form-control" />
        <span asp-validation-for="AboutMe" class="text-danger"></span>
    </div>



    <div class="form-group">
        <input  type="submit" value="Kaydet" class="btn btn-success" />
    </div>
</form>